logging:
  level: INFO
  loggers:
    org.todo: DEBUG

username: Vikash

server:
  applicationConnectors:
    - type: http
      port: 8080

database:
  driverClass: org.sqlite.JDBC
  user: todouser
  password: pass123
  url: jdbc:sqlite:tdlist
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.SQLiteDialect  #org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate.hbm2ddl.auto: create
#  maxWaitForConnection: 1s
#
#  # the SQL query to run when validating a connection's liveness
#  validationQuery: "/* MyService Health Check */ SELECT 1"
#
#  # the timeout before a connection validation queries fail
#  validationQueryTimeout: 3s
#
#  # the minimum number of connections to keep open
#  minSize: 8
#
#  # the maximum number of connections to keep open
#  maxSize: 32
#
#  # whether or not idle connections should be validated
#  checkConnectionWhileIdle: false
#
#  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
#  evictionInterval: 10s
#
#  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
#  minIdleTime: 1 minute