logging:
  level: INFO
  loggers:
    org.todo: DEBUG

username: Vikash

server:
  applicationConnectors:
    - type: http
      port: 8080

database:
  driverClass: org.sqlite.JDBC
  user: todouser
  password: pass123
  url: jdbc:sqlite:tdlist
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.SQLiteDialect  #org.hibernate.dialect.MySQL5InnoDBDialect
